language: python
python:
  - "2.7"

install:
  - "pip install rawes"
  - "sudo useradd shinken"
  - "pip install -r requirements.txt"

script: nosetests -vx --with-coverage --cover-package=module

notifications:
  email: false